// Auto-generated from https://cocoandkandy.com/ — run: node scripts/fetch-supplier-catalog.mjs coco-kandy
// 76 products via shopify-json (Coco & Kandy Crew)

export const cocoKandyProducts = [
  {
    "category": "shirts",
    "name": "Linen Shirt",
    "brand": "EasyWear",
    "price": 141.67,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% premium linen lightweight breathable sustainable fabric",
    "details": "Fabric: 100% Premium Linen Lightweight breathable sustainable fabric Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–XL",
    "imageHint": "shirt",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/LinenShirt.png?v=1753769249",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/linen-shirt",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Shirt Dress by EasyWear",
    "brand": "EasyWear",
    "price": 175,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% premium linen",
    "details": "Fabric: 100% Premium Linen Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–XL",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Shirt_Dress_Linen.jpg?v=1713354907",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/shirt-dress-by-easywear",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Linen Skirt by EasyWear",
    "brand": "EasyWear",
    "price": 158.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric: 100% Premium Sustainable Linen Styling: Designed for a relaxed oversized fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/image00015_2.jpg?v=1713355306",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/linen-skirt-by-easywear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Skye Supima T-shirt",
    "brand": "Coco & Kandy",
    "price": 70,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight fabric 150g",
    "details": "Fabric: 100% Supima® Cotton Lightweight fabric 150g/m2 Styling: Designed for a more fitted fit. Effortlessly pair it with skirts, pants or shorts, it’s the versatile t-shirt that no wardrobe should be without. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Skye-T-shirt-scaled-e1701724799360.jpg?v=1711628679",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/skye-supima-t-shirt",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Maya Summer Dress",
    "brand": "Coco & Kandy",
    "price": 133.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "L–XS",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/J0A9527-scaled-e1701725843584.jpg?v=1711628663",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/maya-summer-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Calypso Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% gots organic cotton",
    "details": "Fabric: 100% GOTS Organic Cotton Weight 181 g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "M–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/CalypsoMaxiDressBack-01-scaled-e1701632995245.jpg?v=1711628632",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/calypso-maxi-dress-2",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Yarra Linen Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric: 100% Premium Linen Jersey Lightweight breathable sustainable fabric Styling: Designed for a relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/bluedress01-Copy.png?v=1711628626",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/yarra-linen-dress",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Sierra Kimono",
    "brand": "Coco & Kandy",
    "price": 150,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "90% vegan silk & 10% lightweight jersey fabric 160g",
    "details": "Fabric: SUPIMA® Cotton 90% Vegan Silk 10% Lightweight jersey fabric 160g/m2 Styling: Can be worn with a belt or relaxed . Care Instructions: Hand Wash Do not bleach Air Dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "One size",
    "imageHint": "cap",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Kimono-Silk-Supima-Side-scaled-e1701105969497.jpg?v=1711628609",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/sierra-kimono-supima-vegan-silk",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Marissa Boat Neck Shift Dress",
    "brand": "vendor-unknown",
    "price": 145,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% lenzing modal® & 4% elastane fabric is wrinkle free micromodal medium",
    "details": "Fabric: 96% Lenzing Modal® 4% Elastane Fabric is wrinkle free MicroModal medium weight 340g/m2 Styling: Designed for a semi-close fit. If you prefer a more fitted look, can easily go a size down as the fabric offers comfortable stretch for better movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "S–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Marissa-Bordeaux-Front-Coco-Kandy-2-scaled.jpg?v=1711628600",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/marissa-dress-fitted-shift-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Calypso Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% recycled polyester",
    "details": "Fabric: 100% Recycled Polyester Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Calypso-Maxi-dress-Front-scaled-e1699867502792_174f82c0-a377-40f2-b307-f1aa59e06de5.jpg?v=1711628587",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/calypso-maxi-dress-1",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Linen Cropped Top",
    "brand": "EasyWear",
    "price": 85,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "Light Blue|Black",
    "swatch": "#60a5fa",
    "accent": "#0b1f3a",
    "fabric": "100% premium linen lightweight breathable sustainable fabric",
    "details": "Fabric: 100% Premium Linen Lightweight breathable sustainable fabric Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–XL",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/TopandShortsLinen.jpg?v=1713353973",
    "colourImages": "{\"Light Blue\":\"https://cdn.shopify.com/s/files/1/0734/7493/3002/files/TopandShortsLinen.jpg?v=1713353973\",\"Black\":\"https://cdn.shopify.com/s/files/1/0734/7493/3002/files/TopandShortsLinen.jpg?v=1713353973\"}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/linen-cropped-top",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Yarra Linen Dress",
    "brand": "Coco & Kandy",
    "price": 125,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric: 100% Premium Linen Jersey Lightweight breathable sustainable fabric Styling: Designed for a relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/YarraLinenDress2.jpg?v=1713367232",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/linen-beach-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Maeva Dress",
    "brand": "Coco & Kandy",
    "price": 150,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% supima® cotton & 4% elastane medium",
    "details": "Fabric: 96% Supima® Cotton 4% Elastane Medium weight jersey fabric 190g/m2 Styling note: Fitted style designed with fabric that is stretchy and allows movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Maeva_Mini_Dress.jpg?v=1713210961",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/short-dress-blue",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Solana Skirt and Top",
    "brand": "Coco & Kandy",
    "price": 125,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% bamboo & 4% elastane medium",
    "details": "Fabric: 96% Bamboo 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed fit, however you can go a size down for more fitted style or up to wear it as a maxi dress. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–S",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Solana-Set-skirt-and-top-STUDIO-scaled.jpg?v=1711628517",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/solana-skirt-and-top",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Linen Maxi Dress - Sunlight by EasyWear",
    "brand": "EasyWear",
    "price": 200,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% premium linen",
    "details": "Fabric: 100% Premium Linen Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours Colour: Light grey and white",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "xXS–XL",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Linen_Dress.png?v=1752043382",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/linen-maxi-dress-by-easywear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Makani Luxe T-Shirt-Black",
    "brand": "Coco & Kandy",
    "price": 60,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "87% tencel & 13% elastane standard 100 oeko-tex certified",
    "details": "Fabric: 87% Tencel 13% Elastane Standard 100 Oeko-Tex certified, the fiber in our PYRATEX® power fabrics originates and are produced in Austria: they are renewable, wood-based fibers, developed with various tree species, including eucalyptus, spruce, pine, birch and beech. 275g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Makani-Luxe-T-shirt-Black.jpg?v=1711628608",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/makani-luxe-t-shirt-black",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Luxury Linen Nordic Blue Trousers",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% belgian linen lightweight fabric 190g",
    "details": "Fabric: 100% Belgian Linen Lightweight fabric 190g/m2 Styling: Trousers that allows movement and comfort. Designed by us, styled by you to wear whenever or wherever. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/pants_blue-scaled.jpg?v=1711628583",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/luxury-linen-nordic-blue-trousers",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Rose Open Back Top",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "63% tencel™ lyocell & 31% cotton & 6% elastane lightweight jersey fabric 155g",
    "details": "Fabric: 63% TENCEL™ Lyocell 31% Cotton 6% Elastane Lightweight jersey fabric 155g/m Styling: Designed for a fitted style. Can go a size down as the fabric offers stretch and movement. The colour of the garment is in the nude tones. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/COVER-3-ROSE-1-e1664905275140.jpg?v=1711628563",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/rose-open-back-top",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Sierra Wide Leg Trousers",
    "brand": "Coco & Kandy",
    "price": 135,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% lenzing modal® & 4% elastane medium",
    "details": "Fabric: 96% Lenzing Modal® 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed oversized fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/AirBrush_20220822212106-1-e1666967074502.jpg?v=1711628543",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/sierra-trousers-modal",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Sierra Wide Leg Trousers",
    "brand": "Coco & Kandy",
    "price": 135,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "88% silk & 10% cashmere & 2% lightweight jersey fabric 100g",
    "details": "Fabric: Lyocell 88% Silk 10% Cashmere 2% Lightweight jersey fabric 100g/m2 Styling: Sheer and stretchy fabric that allows movement and comfort. Designed by us, styled by you to wear whenever or wherever. Care Instructions: Hand wash only Do not bleach Flat dry Iron on low temperature inside out",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "One",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/AirBrush_20220827085857-e1662562107853.jpg?v=1711628513",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/sierra-palazzo-cashmeretrousers",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Makani Luxe T-Shirt",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% viscose & 4% elastane medium",
    "details": "Fabric: 96% Viscose 4% Elastane Medium weight jersey fabric 200g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Makani-Halie-Web-scaled.jpg?v=1711628494",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/makani-luxe-t-shirt",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Alina Mini Shirt Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "53% cupro & 47% lenzing™ ecovero™ medium",
    "details": "Fabric: 53% Cupro, 47% LENZING™ ECOVERO™ Medium weight jersey 200g2m Styling: Designed for a semi-close fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Alina_Dress_Cupro_Studio.jpg?v=1713204389",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/alina-shirt-dress",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Alya Organic Cotton Top - Long Sleeve",
    "brand": "Coco & Kandy",
    "price": 58.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% gots certified organic cotton & 5% elastane lightweight jersey fabric 170g",
    "details": "Fabric: 95% GOTS Certified Organic Cotton 5% Elastane Lightweight jersey fabric 170g/m2 Styling: Designed for a relaxed fit. The fabric offers stretch for comfort and movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Alya_Top_Long_Sleeve.jpg?v=1713205089",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/alya-long-sleeve-top",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Coral Oversized Tee",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Styling: Designed for a relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/CoralOversizedTee-Pink_97dec296-41ef-4ab6-bd7b-3916ba72e4d4.jpg?v=1713351066",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/coral-oversized-t-shirt-pink",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Coral Oversized Tee",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Styling: Designed for a relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/20220307_CocoAndCandy_0303-scaled-e1649754753348.jpg?v=1711628430",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/coral-oversized-tee",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gaia Lyocell-Cashmere Top",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "88% silk & 10% cashmere & 2% lightweight jersey fabric 100g",
    "details": "Fabric: Lyocell 88% Silk 10% Cashmere 2% Lightweight jersey fabric 100g/m2 Styling: Sheer and stretchy fabric that allows movement and comfort. Designed by us, styled by you to wear whenever or wherever. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/29.-Gaia-Top-Side-scaled-e1653550497810.jpg?v=1711628406",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/gaia-lyocell-cashmere-top",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Avani Lyocell Mini Dress",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric: 100% Tencel™ Lyocell Styling note: Fitted style designed with fabric that is stretchy and allows movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/1.-AVANI-OUTER-SPACE-BLUE-2cr.jpg?v=1711628388",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/avani-lyocell-mini-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Lily Long Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% tencel lyocell",
    "details": "Fabric: 100% Tencel Lyocell Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/1.-Lily-Black.jpg?v=1711628374",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/lily-maxi-dress-black",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Lily Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% tencel lyocell",
    "details": "Fabric: 100% Tencel Lyocell Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Lily-Maxi-Dress-Navy-e1681368409193.jpg?v=1711628494",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/maxi-dress-summer-2022",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Kaia Wrap Skirt Grey",
    "brand": "Coco & Kandy",
    "price": 90,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Kaia_Skirt_Modal_Studio.jpg?v=1713210125",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/kaia-wrap-skirt-grey",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Kaia Wrap Skirt Pink",
    "brand": "Coco & Kandy",
    "price": 90,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "shorts",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/20220307_CocoAndCandy_0205-scaled-e1648157942952.jpg?v=1713370895",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/kaia-wrap-skirt-pink",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Ibiza White Sarong",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% viscose & 5% elastane lightweight jersey fabric 50g",
    "details": "Fabric: 95% Viscose 5% Elastane Lightweight Jersey fabric 50g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/PSX_20210812_175949.jpg?v=1711628328",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/ibiza-white-sarong",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Sunset Sarong by GC",
    "brand": "Gina Cusachs",
    "price": 92.5,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "60% organic cotton & 40% viscose",
    "details": "Fabric: 60% organic cotton 40% Viscose Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/KLM2723.jpg?v=1711628317",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/sunset-sarong-gc",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Bek & Meri - Small Sepik Bilum",
    "brand": "vendor-unknown",
    "price": 130,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Natural fibre Sepik bilum, patterned, small, continuous shoulder strap. Bilums are handmade from natural fibres which creates uniqueness and authenticity. It is possible some natural colour change to ocure over time while expose to sun or other conditions. DO NOT WASH",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/NFPT1954-Bilum_1578acc2-a01c-4565-b117-98633a301dfa.jpg?v=1713371907",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/bek-meri-small-sepik-bilum-beachbag",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Bek & Meri - Ink Bilum",
    "brand": "vendor-unknown",
    "price": 135,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Natural fibre bilum, medium size, knot tie shoulder strap. Bilums are handmade from natural fibres which creates uniqueness and authenticity. Some natural colour change may occur over time while expose to sun or other conditions. DO NOT WASH",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/PSX_20210701_113420.jpg?v=1713207581",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/bek-meri-ink-bilum",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Bek & Meri Natural Bilum",
    "brand": "Bek & Meri",
    "price": 200,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Natural Plant fibre (Tulip) bilum, medium size. Bilums are handmade from natural fibres which creates uniqueness and authenticity. Some natural colour change may occur over time while expose to sun or other conditions. DO NOT WASH",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Bilum-1-Natural.jpg?v=1711628378",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/bek-meri-natural-bilum",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Bek & Meri - Earth Tones Bilum",
    "brand": "Bek & Meri",
    "price": 203.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Natural fibre bilum, medium size, knot tie shoulder strap. Bilums are handmade from natural fibres which creates uniqueness and authenticity. Some natural colour change may occur over time while expose to sun or other conditions. DO NOT WASH",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/NFPT2053-BILUM.jpg?v=1711628361",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/colourful-beach-bag-bilum-handmade",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Yellow One Piece by Freeze the Breeze",
    "brand": "Freeze the Breeze",
    "price": 80,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "85% polyamide",
    "details": "Fabric: 85% Polyamide,15% Elastane Lining: PA 82%, EA 18% 200g/m2 Fully lined Care Instructions: Cold hand wash. Do not iron. Rinse after contact with salt or chlorine water.",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "S",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/image00008.jpg?v=1711628311",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/freeze-the-breeze-monaco-one-piece-swimsuit",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Marea Long sleeve Dress",
    "brand": "Coco & Kandy",
    "price": 105,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "48% supima® cotton & 48% wool & 4% elastane medium",
    "details": "Fabric: 48% Supima® Cotton 48% Wool 4% Elastane Medium weight jersey 250g2m Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Marea_Long_Sleeves_Wool_Dress_2.jpg?v=1713362262",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/marea-wool-dress",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Bek & Meri - Natural Fibre Bilum",
    "brand": "vendor-unknown",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Natural fibre bilum, plain, medium size, knot tie shoulder strap. Due to the handmade process and traditional fibres used to create your piece, imperfections are normal and add to the charm of your piece. Some natural softening and colour change may occur over time. DO NOT WASH • Store your piece in a sealed box for a long life. • Take great care if wearing jewellery with your Bilum as fibres can easily catch. • Avoid contact with make-up, lotions, perfumes or hairspray. • Avoid contact with pal",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/BilumBasic-Copy.jpg?v=1713371675",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/natural-fiber-beach-bag-bilum",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Avani Mini Dress-Organic Cotton",
    "brand": "Coco & Kandy",
    "price": 75,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% organic cotton & 4% elastane medium",
    "details": "Fabric: 96% Organic Cotton 4% Elastane Medium weight jersey fabric 170g/m2 Styling note: Fitted style. Please refer to our Item size details. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–M",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/1.3.-AVANI-DRESS-GREEN-6.jpg?v=1711628261",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/avani-organic-cotton-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Avani Mini Black Dress",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% bamboo & 4% elastane medium",
    "details": "Fabric: 96% Bamboo 4% Elastane Medium weight jersey fabric 240g/m2 Styling note: Fitted style. The gentle stretch of the fabric provides comfort and ease of movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Avani_Black_Mini_Dress_Life_Side.jpg?v=1713206921",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/avani-mini-black-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Aria Short Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 125,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% bamboo & 4% elastane medium",
    "details": "Fabric: 96% Bamboo 4% Elastane Medium weight jersey fabric 280g/m2 Styling: Designed for a relaxed fit. Endlessly versatile, you can wear it with heels and statement jewellery for an event or dress it down with sneakers for a cool, casual look. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Aria_Dress_Yello_Maxi_Life_Beach_2.jpg?v=1713206160",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/aria-short-maxi-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Aria Pink Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 125,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Styling: Designed for a relaxed fit. Endlessly versatile, you can wear it anywhere and everywhere. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/2.2.ARIADRESSPINK1.jpg?v=1713205840",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/aria-pink-maxi-short-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Abelia Supima Dress",
    "brand": "Coco & Kandy",
    "price": 129.17,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima cotton lightweight fabric 150g",
    "details": "Fabric: 100% Supima Cotton Lightweight fabric 150g/m2 Styling: Petite size. Designed for a relaxed fit. Dress this stunning piece up with statement heels or keep it casual with a pair of classic flats. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Abelia_Dress_Black_Life.jpg?v=1713202601",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/abelia-black-supima-t-shirt-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Heather Mini Grey Dress",
    "brand": "Coco & Kandy",
    "price": 129.17,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Slightly fitted, can go a size up for more relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/4.3.-HEATHER-Grey-front.jpg?v=1711628180",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/heather-most-comfortable-mini-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Heather Mini Pink Dress",
    "brand": "Coco & Kandy",
    "price": 129.17,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Slightly fitted, can go a size up for more relaxed style. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/4.2.HEATHERDRESSPINK1.jpg?v=1713352199",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/heather-pink-mini-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Noelani Maxi Black Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed fit, however you can go a size down for more fitted style or up to wear it as a maxi dress. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Noelani-Long-Dress-with-side-Split-e1667400761693_8fb9841b-b96f-4874-9af2-68c6af5c8079.png?v=1711628225",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/noelani-black-long-dress-with-side-split",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Noelani Maxi Pink Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% tencel™ modal & 4% elastane medium",
    "details": "Fabric: 96% TENCEL™ Modal 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed fit, however you can go a size down for more fitted style or size up as a maxi dress. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/NOELANI-PINK-GREY-COVER-scaled.jpg?v=1711628221",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/noelani-pink-maxi-dress-with-side-split",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Marguerite Open Back Lyocell Dress",
    "brand": "vendor-unknown",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% tencel™ lyocell lightweight jersey fabric 150g",
    "details": "Fabric: 100% Tencel™ Lyocell Lightweight jersey fabric 150g/m2 Styling: Designed for a fitted style. Can go a size down as the fabric offers stretch and movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Marguerite-Navy-Lyocell-back-Coco-Kandy-scaled-e1701635476295.jpg?v=1711628196",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/marguerite-open-back-dress-dark-blue",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Marguerite Lyocell Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "63% tencel™ lyocell & 31% cotton & 6% elastane lightweight jersey fabric 155g",
    "details": "Fabric: 63% TENCEL™ Lyocell 31%Cotton 6%Elastane Lightweight jersey fabric 155g/m Styling: Designed for a fitted style. Can go a size down as the fabric offers stretch and movement. The colour of the garment is in the nude tones. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/MG_3218r-Copy.jpg?v=1711628149",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/marguerite-lyocell-dress-rose",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Dakota Organic Cotton",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% organic cotton & 4% elastane medium",
    "details": "Fabric: 96% Organic Cotton 4% Elastane Medium weight jersey fabric 170g/m2 S tyling: Designed for a fitted style, can go a size up for more relaxed fit. Can easily wear the back as a front to change the look of the neckline. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/7.3.-DAKOTA-Green_4d053e8e-a7c3-44a6-97bf-86df28e69b10.jpg?v=1713372256",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/dakota-organic-cotton",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Dakota Bamboo Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 280g/m2 S tyling: Versatile design that can be worn anywhere and everywhere. Designed for a fitted style, can go a size up for more relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/7.1.-DAKOTA-DRESS-YELLOW-1.1.jpg?v=1711628090",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/dakota-bamboo-dress-yellow",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Savannah Pink Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed oversized fit. The fabric we used has added stretch. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/AirBrush_20211203204153.jpg?v=1711628132",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/savannah-maxi-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Hali Wool Midi Dress",
    "brand": "Coco & Kandy",
    "price": 187.5,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "48% supima® cotton & 48% wool & 4% elastane medium",
    "details": "Fabric: 48% Supima® Cotton 48% Wool 4% Elastane Medium weight jersey 250g2m Styling: Designed for a semi-close fit. If you prefer a more fitted look, can easily go a size down as the fabric offers comfortable stretch for better movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/9.2.HALIDRESSBLACK3.-Copy.jpg?v=1713371504",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/hali-wool-dress-black",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Ember Modal Dress",
    "brand": "Coco & Kandy",
    "price": 125,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% lenzing modal® & 4% elastane the fabric is wrinkle free",
    "details": "Fabric: 96% Lenzing Modal® 4% Elastane The fabric is wrinkle free with medium weight 340g/m2. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Ember-Bordeaux-side-Coco-Kandy-scaled.jpg?v=1711628089",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/ember-bordeaux-dress",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Lilou Supima Top",
    "brand": "Coco & Kandy",
    "price": 50,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight jersey fabric 150g",
    "details": "Fabric: 100% Supima® Cotton Lightweight jersey fabric 150g/m2 Curved Hemline Styling: Can wear a size up for more relax fit. Non stretchy fabric. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/13.1.-LILOU-TOP-WHITE-4.jpg?v=1711628059",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/lilou-supima-top",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Kawai Organic Cotton Tee",
    "brand": "Coco & Kandy",
    "price": 60,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% organic cotton & 4% elastane medium",
    "details": "Fabric: 96% Organic Cotton 4% Elastane Medium weight jersey fabric 170g/m2 Styling: Designed for a relaxed fit. The fabric offers stretch and comfort. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/12.1.KAWAITEEGREEN6.jpg?v=1713352475",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/kawai-organic-cotton-tee",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Kawai Supima Tee - White",
    "brand": "Coco & Kandy",
    "price": 70,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight fabric 150g",
    "details": "Fabric: 100% Supima® Cotton Lightweight fabric 150g/m2 Styling: Designed for a relaxed fit. Effortlessly pair it with skirts, pants or shorts, it’s the versatile t-shirt that no wardrobe should be without. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/MG_4934.jpg?v=1711628013",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/kawai-supima-t-shirt-white",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Nixie Supima Tee - White",
    "brand": "Coco & Kandy",
    "price": 60,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight fabric 150g",
    "details": "Fabric: 100% Supima® Cotton Lightweight fabric 150g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/14.1.-NIXIE-TEE-WHITE-3.jpg?v=1711628003",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/nixie-supima-t-shirt-white",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Nixie Classic Blue Supima Cotton Tee",
    "brand": "Coco & Kandy",
    "price": 60,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% supima® cotton & 4% elastane lightweight fabric 150g",
    "details": "Fabric: 96% Supima® Cotton 4% Elastane Lightweight fabric 150g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/png_20220715_155511_0000-e1657889919537.png?v=1711628078",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/nixie-blue-supima-cotton-t-shirt",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Nixie Supima Tee - Black",
    "brand": "Coco & Kandy",
    "price": 60,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight fabric 150g",
    "details": "Fabric: 100 % Supima® Cotton Lightweight fabric 150g/m2 Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/14.2-NIXIE-TEE-BLACK-2.jpg?v=1711628038",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/nixie-supima-cotton-luxury-t-shirt-black",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Kawai Supima Tee - Black",
    "brand": "Coco & Kandy",
    "price": 70,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% supima® cotton lightweight fabric 150g",
    "details": "Fabric: 100% Supima® Cotton Lightweight fabric 150g/m2 Styling: Designed for a relaxed fit. Effortlessly pair it with skirts, pants or shorts, it’s the versatile t-shirt that no wardrobe should be without. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/12.3.-KAWAI-BLACK4-front-1.jpg?v=1711628007",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/kawai-supima-t-shirt-black",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Ember Little Black Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey 250g2m Styling: Designed for a semi-close fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/PSX_20220828_105049-scaled-e1661701714268.jpg?v=1711627999",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/ember-little-black-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Gaia Lyocell Cashmere Dress",
    "brand": "Coco & Kandy",
    "price": 90,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "88% silk & 10% cashmere & 2% lightweight jersey fabric 100g",
    "details": "Fabric: Lyocell 88% Silk 10% Cashmere 2% Lightweight jersey fabric 100g/m2 Styling: Sheer and stretchy fabric that allows movement and comfort. Designed by us, styled by you to wear whenever or wherever. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "One size",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/GAIA-FRONT-PAGE2.jpg?v=1711627976",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/gaia-lyocell-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Sana Long Sleeve Maxi Dress",
    "brand": "Coco & Kandy",
    "price": 90,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% gots certified organic cotton & 5% elastane lightweight jersey fabric 170g",
    "details": "Fabric: 95% GOTS Certified Organic Cotton 5% Elastane Lightweight jersey fabric 170g/m2 Styling: Designed for a relaxed fit. The fabric offers stretch for comfort and movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/10.SANADRESSGREY1..jpg?v=1713364193",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/sana-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Hali Midi Bordeaux Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% lenzing modal® & 4% elastane wrinkle free micromodal medium",
    "details": "Fabric: 96% Lenzing Modal® 4% Elastane Wrinkle free MicroModal medium weight 340g/m2 Styling: Designed for a semi-close fit. If you prefer a more fitted look, can easily go a size down as the fabric offers comfortable stretch for better movement.. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/PSX_20220823_201213-scaled.jpg?v=1711627923",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/hali-bordeaux-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Savannah Maxi Dress - Grey",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% lenzing modal® & 4% elastane medium",
    "details": "Fabric: 96% Lenzing Modal® 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Designed for a relaxed oversized fit. The fabric we used has added stretch so can easy go a size down. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/8.1.-SAVANNAH-Grey-side.jpg?v=1711627967",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/savannah-dress-grey",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Dakota Long Bamboo Dress",
    "brand": "Coco & Kandy",
    "price": 165,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 240g/m2 S tyling: Versatile design that can be worn anywhere and everywhere. Designed for a fitted style, can go a size up for more relaxed fit. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/7.2.-DAKOTA-DRESS-BLACK-1.1-scaled.jpg?v=1711627935",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/dakota-bamboo-dress-black",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Heather Supima Mini Dress",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% supima® cotton & 4% elastane medium",
    "details": "Fabric: 96% Supima® Cotton 4% Elastane Medium weight jersey fabric 190g/m2 Styling: True to size, slightly fitted, can go a size up for more relaxed style. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Heather-Dress-scaled.jpg?v=1711627923",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/heather-supima-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Abelia Bamboo Dress",
    "brand": "Coco and Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 280g/m2 Styling: Designed for a relaxed fit. Dress this stunning piece up with statement wedges or keep it casual with a pair of strappy flats. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/Abelia-Mini-Dress-Yellow-Studio.jpg?v=1713192498",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/abelia-bamboo-dress",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Lilou Lyocell Top",
    "brand": "Coco & Kandy",
    "price": 70,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "100% tencel™ lyocell lightweight jersey fabric 150g",
    "details": "Fabric: 100% Tencel™ Lyocell Lightweight jersey fabric 150g/m2 Details: Curved Hemline. Non stretchy fabric. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "polo",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/13.2-LILOU-Copy.jpg?v=1711627878",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/lilou-top",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Noelani Dress - Grey",
    "brand": "Coco & Kandy",
    "price": 166.67,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240g/m2 Styling: Wear size up for more relax fit or a size down for fitted style. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/5.1.-NOELANI-DRESS-GREY-4.-scaled-e1662569533832.jpg?v=1711627858",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/noelani-grey-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Marguerite Midi Dress",
    "brand": "Coco & Kandy",
    "price": 183.33,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "95% bamboo & 5% elastane medium",
    "details": "Fabric: 95% Bamboo 5% Elastane Medium weight jersey fabric 240g/m2 Styling Notes: Designed for a fitted style. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/6.2.-MARGUERITE-DRESS-BLACK-3-Copy.jpg?v=1711627900",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/marguerite-midi-dress",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Aria Dress Grey",
    "brand": "Coco & Kandy",
    "price": 100,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% modal & 4% elastane medium",
    "details": "Fabric: 96% Modal 4% Elastane Medium weight jersey fabric 240 g/m2 Styling advice: Designed for a relaxed fit. Endlessly versatile, you can wear it with heels and statement jewellery for an event or dress it down with sneakers for a cool, casual look. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/1.ARIAGREY.jpg?v=1713370803",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/aria-short-dress-grey",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Avani Supima Mini Dress",
    "brand": "Coco & Kandy",
    "price": 166.67,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#e2e8f0",
    "accent": "#0b1f3a",
    "fabric": "96% supima® cotton & 4% elastane medium",
    "details": "Fabric: 96% Supima® Cotton 4% Elastane Medium weight jersey fabric 190g/m2 Styling note: Fitted style designed with fabric that is stretchy and allows movement. Care Instructions: Wash 30° Do not bleach Do not tumble dry Iron on low temperature Do not dry clean Wash inside out with similar colours",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "XS–L",
    "imageHint": "dress",
    "imageUrl": "https://cdn.shopify.com/s/files/1/0734/7493/3002/files/AvaniMiniDress-ClassicBlue-Full-size.jpg?v=1713371313",
    "colourImages": "{}",
    "supplierName": "Coco & Kandy Crew",
    "productUrl": "https://cocoandkandy.com/products/avani-mini-dress",
    "active": "true"
  }
];
