// Auto-generated from https://oceanr.co/ — run: node scripts/fetch-supplier-catalog.mjs oceanr
// 5 products via woocommerce-store-api (OceanR)

export const oceanrProducts = [
  {
    "category": "tops",
    "name": "Custom Jackets",
    "brand": "OceanR",
    "price": 0,
    "currency": "USD",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "[vc_row type=”full_width_background” full_screen_row_position=”middle” column_margin=”default” column_direction=”default” column_direction_tablet=”default” column_direction_phone=”default” bg_color=”#ffffff” scene_position=”center” top_padding=”0″ constrain_group_1=”yes” bottom_padding=”0″ text_color=”dark” text_align=”left” row_border_radius=”none” row_border_radius_applies=”bg” overflow=”visible” id=”core-features” row_name=”Core Features” overlay_strength=”0.3″ gradient_direction=”left_to_rig",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets6.jpg",
    "colourImages": "{\"OCEANR Custom Jackets6\":\"https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets6.jpg\",\"OCEANR Custom Jackets5\":\"https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets5.jpg\",\"OCEANR Custom Jackets3\":\"https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets3.jpg\",\"OCEANR Custom Jackets2\":\"https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets2.jpg\",\"OCEANR Custom Jackets1\":\"https://oceanr.co/wp-content/uploads/2024/04/OCEANR-Custom-Jackets1.jpg\"}",
    "supplierName": "OceanR",
    "productUrl": "https://oceanr.co/product/custom-branded-jackets/",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Custom Eco-friendly Water Bottles",
    "brand": "OceanR",
    "price": 0,
    "currency": "USD",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "[vc_row type=”in_container” full_screen_row_position=”middle” column_margin=”default” column_direction=”default” column_direction_tablet=”default” column_direction_phone=”default” scene_position=”center” left_padding_desktop=”5%” constrain_group_2=”yes” right_padding_desktop=”5%” text_color=”dark” text_align=”left” row_border_radius=”none” row_border_radius_applies=”bg” overflow=”visible” overlay_strength=”0.3″ gradient_direction=”left_to_right” shape_divider_position=”bottom” bg_image_animation",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Water-Bottle.png",
    "colourImages": "{\"Water Bottle designed for Four Seasons retail\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Water-Bottle.png\",\"Sustainable Custom Water Bottles for Luxury Hotels\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Water-Bottle-2.png\",\"Custom water bottles for event merchandise\":\"https://oceanr.co/wp-content/uploads/2023/10/IYCBottle_01.jpg\",\"Eco-friendly water bottle with custom bamboo lid\":\"https://oceanr.co/wp-content/uploads/2023/10/IYCBottle_02.jpg\",\"Eco-friendly water bottles custom designs\":\"https://oceanr.co/wp-content/uploads/2023/10/IYCBottle_03.jpg\"}",
    "supplierName": "OceanR",
    "productUrl": "https://oceanr.co/product/custom-water-bottles/",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Custom Board Shorts",
    "brand": "OceanR",
    "price": 0,
    "currency": "USD",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "[vc_row type=”in_container” full_screen_row_position=”middle” column_margin=”default” column_direction=”default” column_direction_tablet=”default” column_direction_phone=”default” scene_position=”center” left_padding_desktop=”5%” constrain_group_2=”yes” right_padding_desktop=”5%” text_color=”dark” text_align=”left” row_border_radius=”none” row_border_radius_applies=”bg” overflow=”visible” overlay_strength=”0.3″ gradient_direction=”left_to_right” shape_divider_position=”bottom” bg_image_animation",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Board-Shorts.png",
    "colourImages": "{\"OCEANR Custom Board Shorts\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Board-Shorts.png\",\"OCEANR Custom Board Shorts-2\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Board-Shorts-2.png\",\"OCEANR Custom Board Shorts-1\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Board-Shorts-1.png\",\"OCEANR Custom Board Shorts-3\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Board-Shorts-3.png\"}",
    "supplierName": "OceanR",
    "productUrl": "https://oceanr.co/product/custom-board-shorts/",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Custom Polo Shirts",
    "brand": "OceanR",
    "price": 0,
    "currency": "USD",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "[vc_row type=”in_container” full_screen_row_position=”middle” column_margin=”default” column_direction=”default” column_direction_tablet=”default” column_direction_phone=”default” scene_position=”center” left_padding_desktop=”5%” constrain_group_2=”yes” right_padding_desktop=”5%” text_color=”dark” text_align=”left” row_border_radius=”none” row_border_radius_applies=”bg” overflow=”visible” overlay_strength=”0.3″ gradient_direction=”left_to_right” shape_divider_position=”bottom” bg_image_animation",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Polo.png",
    "colourImages": "{\"OCEANR Custom Polo\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Polo.png\",\"OCEANR Custom Polo-3\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Polo-3.png\",\"OCEANR Custom Polo-2\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Polo-2.png\",\"OCEANR Custom Polo-1\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Polo-1.png\"}",
    "supplierName": "OceanR",
    "productUrl": "https://oceanr.co/product/custom-polo-shirts/",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Custom Tech Tees",
    "brand": "OceanR",
    "price": 0,
    "currency": "USD",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "[vc_row type=”in_container” full_screen_row_position=”middle” column_margin=”default” column_direction=”default” column_direction_tablet=”default” column_direction_phone=”default” scene_position=”center” left_padding_desktop=”5%” constrain_group_2=”yes” right_padding_desktop=”5%” text_color=”dark” text_align=”left” row_border_radius=”none” row_border_radius_applies=”bg” overflow=”visible” overlay_strength=”0.3″ gradient_direction=”left_to_right” shape_divider_position=”bottom” bg_image_animation",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts.png",
    "colourImages": "{\"OCEANR Custom Tech T-shirts\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts.png\",\"OCEANR Custom Tech T-shirts-2\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts-2.png\",\"OCEANR Custom Tech T-shirts-3\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts-3.png\",\"OCEANR Custom Tech T-shirts-4\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts-4.png\",\"OCEANR Custom Tech T-shirts-5\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts-5.png\",\"OCEANR Custom Tech T-shirts-1\":\"https://oceanr.co/wp-content/uploads/2023/10/OCEANR-Custom-Tech-T-shirts-1.png\"}",
    "supplierName": "OceanR",
    "productUrl": "https://oceanr.co/product/custom-tech-tee/",
    "active": "true"
  }
];
