// Auto-generated from https://sea-design.com/ — run: node scripts/fetch-supplier-catalog.mjs sea-design
// 68 products via sea-design-listing (Sea Design)

export const seaDesignProducts = [
  {
    "category": "tops",
    "name": "Dresses & Jumpsuits",
    "brand": "Dresses &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/formal",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Shirts & Blouses",
    "brand": "Shirts &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/formal",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Skorts & Skirts",
    "brand": "Skorts &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/formal",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Shorts & Trousers",
    "brand": "Shorts &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/formal",
    "active": "true"
  },
  {
    "category": "epaulettes",
    "name": "Epaulettes & Accessories",
    "brand": "Epaulettes &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "epaulettes",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/formal",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Shorts",
    "brand": "Shorts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bottoms",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Skorts",
    "brand": "Skorts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bottoms",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Skirts",
    "brand": "Skirts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bottoms",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Trousers",
    "brand": "Trousers",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bottoms",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Ladies' Shirts & Blouses",
    "brand": "Ladies' Shirts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/shirts-blouses",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Men's Shirts",
    "brand": "Men's Shirts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/shirts-blouses",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Ladies' Polos",
    "brand": "Ladies' Polos",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/polos",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Men's Polos",
    "brand": "Men's Polos",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/polos",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Long Sleeve",
    "brand": "Long Sleeve",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/polos",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Ladies' T-Shirts",
    "brand": "Ladies' T-Shirts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/t-shirts",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Men's T-Shirts",
    "brand": "Men's T-Shirts",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/tops/t-shirts",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Fleeces",
    "brand": "Fleeces",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/midlayers",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Knitwear",
    "brand": "Knitwear",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/midlayers",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Hoodies & Sweatshirts",
    "brand": "Hoodies &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/midlayers",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Jackets",
    "brand": "Jackets",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/jackets-gilets-foul-weather",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Softshell",
    "brand": "Softshell",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/jackets-gilets-foul-weather",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gilets / Vests",
    "brand": "Gilets /",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/jackets-gilets-foul-weather",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Foul Weather",
    "brand": "Foul Weather",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/jackets-gilets-foul-weather",
    "active": "true"
  },
  {
    "category": "engineering",
    "name": "Coveralls",
    "brand": "Coveralls",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "engineer"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "overalls",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/engineer-s-workwear",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Trousers & Shorts",
    "brand": "Trousers &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/engineer-s-workwear",
    "active": "true"
  },
  {
    "category": "shoes",
    "name": "Accessories & Footwear",
    "brand": "Accessories &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shoes",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/engineer-s-workwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Chef Jackets",
    "brand": "Chef Jackets",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/chef-wear",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Chef Trousers",
    "brand": "Chef Trousers",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/chef-wear",
    "active": "true"
  },
  {
    "category": "shoes",
    "name": "Chef's Accessories & Footwear",
    "brand": "Chef's Accessories",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shoes",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/chef-wear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Caps & Visors",
    "brand": "Caps &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/headwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Hats",
    "brand": "Hats",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/headwear",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Beanies Knit, Fleece Caps & Knits",
    "brand": "Beanies Knit,",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/headwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Chef",
    "brand": "Chef",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/headwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "All Women",
    "brand": "All Women",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "All Men",
    "brand": "All Men",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "shoes",
    "name": "Trainers",
    "brand": "Trainers",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shoes",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Formal",
    "brand": "Formal",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Slip-Ons",
    "brand": "Slip-Ons",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Safety & Boots",
    "brand": "Safety &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "engineer"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Socks",
    "brand": "Socks",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/footwear",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Bags",
    "brand": "Bags",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bags-more-",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gift items",
    "brand": "Gift items",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bags-more-",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Misc. products",
    "brand": "Misc. products",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/bags-more-",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Sea Design Men's Henry Easy Care Shorts",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Sea Design Anna Easy Care skort",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Stormtech Ladies' Eclipse H2X-Dri piqué polo",
    "brand": "Stormtech Ladies'",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Webbing & Leather Belt",
    "brand": "Webbing &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Sea Design Ladies Fast-Dry shorts",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "Sea Design Men's Deluxe Pilot Shirt",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Cutter & Buck Men's New Salish Pants",
    "brand": "Cutter &",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "Classic Leather Belt with Silver Buckle - 3cm",
    "brand": "Classic Leather",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "Sea Design Ladies Deluxe Pilot Shirt",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Cutter&Buck Ladies' Bonney Lake Pants (7/8th length)",
    "brand": "Cutter&Buck Ladies'",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "Sea Design Custom Laura Wrap Dress",
    "brand": "Sea Design",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "dress",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "James Nicholson Ladies' Cotton Cardigan",
    "brand": "James Nicholson",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Stormtech Women's Greenwich Lightweight Softshell",
    "brand": "Stormtech Women's",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Stormtech Men's Greenwich Lightweight Softshell",
    "brand": "Stormtech Men's",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gildan Softstyle® adult ringspun t-shirt",
    "brand": "Gildan Softstyle®",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gildan Softstyle® women's v-neck t-shirt",
    "brand": "Gildan Softstyle®",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "Wet Effect Adult Unisex Long Sleeve Rash Vest",
    "brand": "Wet Effect",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Stormtech Eclipse H2X-Dri piqué polo",
    "brand": "Stormtech Eclipse",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Wet Effect Men's Board Shorts",
    "brand": "Wet Effect",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Wet Effect Ladies Board Shorts",
    "brand": "Wet Effect",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "Gill Technical UV Sailing Hat",
    "brand": "Gill Technical",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "engineer"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "TriDri Women's Performance Leggings",
    "brand": "TriDri Women's",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman",
    "roleTags": [
      "engineer"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "chef-wear",
    "name": "Chaud Devant Men's Short Sleeve Bacio Chef Jacket",
    "brand": "Chaud Devant",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "chef-jacket",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Chaud Devant Santino Chef Trousers",
    "brand": "Chaud Devant",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "Chaud Devant Lady Stretch Chef Trousers",
    "brand": "Chaud Devant",
    "price": 0,
    "currency": "EUR",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": "",
    "colourImages": "",
    "supplierName": "Sea Design",
    "productUrl": "https://sea-design.com/page/shop/below-deck-collection",
    "active": "true"
  }
];
