// Auto-generated from https://waypointuae.com/ — run: node scripts/fetch-supplier-catalog.mjs waypoint-uae
// 23 products via waypoint-jsonld (Waypoint UAE)

export const waypointUaeProducts = [
  {
    "category": "bottoms",
    "name": "BR2 OFFSHORE TROUSERS 2.0",
    "brand": "Musto",
    "price": 1900,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "ABOUT \n \n \n There's an offshore sailor in everyone with BR2. Featuring Musto's new hardcore BR2 Performance' fabric which offers exceptional 30k/15k waterproof protection, these trousers will keep you completely dry and are designed for intense and frequent, but short duration, offshore sailing expeditions. \n \n \n \n \n COMPOSITION \n \n \n Shell: 100% Cotton - Shell 2: 100% Polyester - Lining: 100%",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BR2 OFFSHORE TROUSERS 2.0",
      "name": "BR2 OFFSHORE TROUSERS 2.0",
      "description": "ABOUT \n \n \n There's an offshore sailor in everyone with BR2. Featuring Musto's new hardcore BR2 Performance' fabric which offers exceptional 30k/15k waterproof protection, these trousers will keep you completely dry and are designed for intense and frequent, but short duration, offshore sailing expeditions. \n \n \n \n \n COMPOSITION \n \n \n Shell: 100% Cotton - Shell 2: 100% Polyester - Lining: 100%",
      "url": "https://waypointuae.com/products/BR2-OFFSHORE-TROUSERS-2-0-p518500500",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691247020.jpg",
      "width": 278,
      "height": 597,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BR2 OFFSHORE TROUSERS 2.0",
        "url": "https://waypointuae.com/products/BR2-OFFSHORE-TROUSERS-2-0-p518500500",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691247021.jpg",
        "width": 186,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691247021.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BR2-OFFSHORE-TROUSERS-2-0-p518500500",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "BR1 Inshore Jacket FW",
    "brand": "Musto",
    "price": 1500,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "This classic Musto jacket is designed to protect you from the unpredictable conditions often experienced when inshore sailing. It has a 2-layer fabrication that's waterproof and breathable to Musto's stringent BR1 standard and is mesh lined for additional comfort against your skin and improved air circulation. There's a double storm flap with a drainage channel covering the zip and an adjustable,",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BR1 Inshore Jacket FW",
      "name": "BR1 Inshore Jacket FW",
      "description": "This classic Musto jacket is designed to protect you from the unpredictable conditions often experienced when inshore sailing. It has a 2-layer fabrication that's waterproof and breathable to Musto's stringent BR1 standard and is mesh lined for additional comfort against your skin and improved air circulation. There's a double storm flap with a drainage channel covering the zip and an adjustable,",
      "url": "https://waypointuae.com/products/BR1-INSHORE-JACKET-FW-p518510295",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417736451.jpg",
      "width": 1500,
      "height": 1500,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BR1 Inshore Jacket FW",
        "url": "https://waypointuae.com/products/BR1-INSHORE-JACKET-FW-p518510295",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417736452.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417736452.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BR1-INSHORE-JACKET-FW-p518510295",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "BR1 SHORTS",
    "brand": "Musto",
    "price": 690,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Made to Musto's exemplary BR1 standard, these BR1 Shorts are ideal for wet decks in fair weather. A reinforced seat panel enhances durability when working on the boat, while a tricot brushed lining provides impressive comfort next to the skin. Elastication in the waist offers a tailored fit while taped seams throughout provide exceptionally dry wear. Available in two colours to complement your",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BR1 SHORTS",
      "name": "BR1 SHORTS",
      "description": "Made to Musto's exemplary BR1 standard, these BR1 Shorts are ideal for wet decks in fair weather. A reinforced seat panel enhances durability when working on the boat, while a tricot brushed lining provides impressive comfort next to the skin. Elastication in the waist offers a tailored fit while taped seams throughout provide exceptionally dry wear. Available in two colours to complement your",
      "url": "https://waypointuae.com/products/BR1-SHORTS-p518510289",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417759714.jpg",
      "width": 1500,
      "height": 1500,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BR1 SHORTS",
        "url": "https://waypointuae.com/products/BR1-SHORTS-p518510289",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417759715.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3417759715.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BR1-SHORTS-p518510289",
    "active": "true"
  },
  {
    "category": "dresses",
    "name": "AUDREY DRESS",
    "brand": "Marinepool",
    "price": 565,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "SKU: 1004243 FABRIC: 85% polyester, 15% elastane FEATURES: Audrey – the only V–neck dress with additional epaulettes. The elegant dress was specially designed for the requirements of the female crew members of superyachts. It is the first uniform dress with epaulettes for rank signs on the market. The easy-care material and the optimal fit make this dress a highlight in modern crew clothing. A",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "dress",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "AUDREY DRESS",
      "name": "AUDREY DRESS",
      "description": "SKU: 1004243 FABRIC: 85% polyester, 15% elastane FEATURES: Audrey – the only V–neck dress with additional epaulettes. The elegant dress was specially designed for the requirements of the female crew members of superyachts. It is the first uniform dress with epaulettes for rank signs on the market. The easy-care material and the optimal fit make this dress a highlight in modern crew clothing. A",
      "url": "https://waypointuae.com/products/AUDREY-DRESS-p521711314",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406510695.jpg",
      "width": 1000,
      "height": 1500,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "AUDREY DRESS",
        "url": "https://waypointuae.com/products/AUDREY-DRESS-p521711314",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406510696.jpg",
        "width": 267,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406510696.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/AUDREY-DRESS-p521711314",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "BR2 OFFSHORE JACKET 2.0",
    "brand": "Musto",
    "price": 2500,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "ABOUT \n \n \n Featuring Musto’s new hardcore ‘BR2 Performance’ fabric which not only offers 30k/15k waterproof protection, it also features our brand new durable DWR, ‘LDWR’ – a long lasting DWR developed using PFC-free chemistry, with a much higher wet abrasion resistance so the fabric stays drier for longer. With design nods to the iconic HPX such as the new spume guard, and an innovated collar",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BR2 OFFSHORE JACKET 2.0",
      "name": "BR2 OFFSHORE JACKET 2.0",
      "description": "ABOUT \n \n \n Featuring Musto’s new hardcore ‘BR2 Performance’ fabric which not only offers 30k/15k waterproof protection, it also features our brand new durable DWR, ‘LDWR’ – a long lasting DWR developed using PFC-free chemistry, with a much higher wet abrasion resistance so the fabric stays drier for longer. With design nods to the iconic HPX such as the new spume guard, and an innovated collar",
      "url": "https://waypointuae.com/products/BR2-OFFSHORE-JACKET-2-0-p518513545",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4183861061.jpg",
      "width": 407,
      "height": 392,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BR2 OFFSHORE JACKET 2.0",
        "url": "https://waypointuae.com/products/BR2-OFFSHORE-JACKET-2-0-p518513545",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4183861062.jpg",
        "width": 400,
        "height": 385
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4183861062.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BR2-OFFSHORE-JACKET-2-0-p518513545",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "BR1 INSHORE JACKET",
    "brand": "Musto",
    "price": 1500,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "The BR1 Coastal Jacket, with its taped seams and exceptional BR1 Musto fabric construction, supplies a superior level of waterproof and windproof protection. Double cuffs a storm flap zip guard and drawcord hem seal water out for exceptional dryness. The technical rollaway, fluorescent hood adds visibility as well as enhances the garment's waterproof protection. The two fleece-lined pockets and",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BR1 INSHORE JACKET",
      "name": "BR1 INSHORE JACKET",
      "description": "The BR1 Coastal Jacket, with its taped seams and exceptional BR1 Musto fabric construction, supplies a superior level of waterproof and windproof protection. Double cuffs a storm flap zip guard and drawcord hem seal water out for exceptional dryness. The technical rollaway, fluorescent hood adds visibility as well as enhances the garment's waterproof protection. The two fleece-lined pockets and",
      "url": "https://waypointuae.com/products/BR1-INSHORE-JACKET-p518505399",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4221996230.jpg",
      "width": 1500,
      "height": 1500,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BR1 INSHORE JACKET",
        "url": "https://waypointuae.com/products/BR1-INSHORE-JACKET-p518505399",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4221996231.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4221996231.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BR1-INSHORE-JACKET-p518505399",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "AGT 32 GLOVES",
    "brand": "Marinepool",
    "price": 199.68,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "FABRIC: 60% polychloroprene, 16% polyamide, 12% amara, 12% PU FEATURES: AGT 32 – the long finger sailing glove with thermal insulation. Thanks to its excellent thermal insulation and Amara reinforcement, the AGT 32 long finger glove is particularly suitable for bad and cold weather. The contrasting stitching not only gives additional reinforcement but also a sportive note. With the help of the",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "AGT 32 GLOVES",
      "name": "AGT 32 GLOVES",
      "description": "FABRIC: 60% polychloroprene, 16% polyamide, 12% amara, 12% PU FEATURES: AGT 32 – the long finger sailing glove with thermal insulation. Thanks to its excellent thermal insulation and Amara reinforcement, the AGT 32 long finger glove is particularly suitable for bad and cold weather. The contrasting stitching not only gives additional reinforcement but also a sportive note. With the help of the",
      "url": "https://waypointuae.com/products/AGT-32-GLOVES-p524602249",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691077658.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "AGT 32 GLOVES",
        "url": "https://waypointuae.com/products/AGT-32-GLOVES-p524602249",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691077659.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691077659.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/AGT-32-GLOVES-p524602249",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "ACTIVE 2 T-SHIRT MEN",
    "brand": "Marinepool",
    "price": 200,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "FABRIC: 84% polyester, 16% spandex FEATURES: The light Active 2 T-Shirt in new high performance quality designed to keep you cool and dry on warm and hot days with quick dry, RUCO bac Med antiperspirant UVP 50+ protection, breathable, moisture wicking. The simple design with round neck and small reflected print at side seam, makes it easy to combine and is ideal for teams and crews or companies.",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "ACTIVE 2 T-SHIRT MEN",
      "name": "ACTIVE 2 T-SHIRT MEN",
      "description": "FABRIC: 84% polyester, 16% spandex FEATURES: The light Active 2 T-Shirt in new high performance quality designed to keep you cool and dry on warm and hot days with quick dry, RUCO bac Med antiperspirant UVP 50+ protection, breathable, moisture wicking. The simple design with round neck and small reflected print at side seam, makes it easy to combine and is ideal for teams and crews or companies.",
      "url": "https://waypointuae.com/products/ACTIVE-2-T-SHIRT-MEN-p524602233",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888802032.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "ACTIVE 2 T-SHIRT MEN",
        "url": "https://waypointuae.com/products/ACTIVE-2-T-SHIRT-MEN-p524602233",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888802033.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888802033.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/ACTIVE-2-T-SHIRT-MEN-p524602233",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "CARGO TEC TROUSERS MEN",
    "brand": "Marinepool",
    "price": 445,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric 90% polyamide, 10% elastane Features Whether for sailing or work wear - functional, lightweight trousers are always required. The 2-way stretch fabric offers the highest level of comfort and freedom of movement. Bar tags in contrast yarn and button stitching gives a modern and sporty look",
    "fit": "woman|man",
    "roleTags": [
      "engineer"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CARGO TEC TROUSERS MEN",
      "name": "CARGO TEC TROUSERS MEN",
      "description": "Fabric 90% polyamide, 10% elastane Features Whether for sailing or work wear - functional, lightweight trousers are always required. The 2-way stretch fabric offers the highest level of comfort and freedom of movement. Bar tags in contrast yarn and button stitching gives a modern and sporty look",
      "url": "https://waypointuae.com/products/CARGO-TEC-TROUSERS-MEN-p524610830",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888836256.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CARGO TEC TROUSERS MEN",
        "url": "https://waypointuae.com/products/CARGO-TEC-TROUSERS-MEN-p524610830",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888836257.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888836257.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CARGO-TEC-TROUSERS-MEN-p524610830",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "ACTIVE 2 LONG SLEEVE",
    "brand": "Marinepool",
    "price": 240,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Fabric: 84% polyester, 16% spandex \n Features: The light Active 2 long sleeve in new high performan�ce quality designed to keep you cool and dry on warm and hot days with quick dry, RUCO bac Med antiperspirant UVP 50+ protection, breathable, moisture wicking. The simple design with round neck and small reflected print at side seam, makes it easy to combine and is ideal for teams and crews or",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "ACTIVE 2 LONG SLEEVE",
      "name": "ACTIVE 2 LONG SLEEVE",
      "description": "Fabric: 84% polyester, 16% spandex \n Features: The light Active 2 long sleeve in new high performan�ce quality designed to keep you cool and dry on warm and hot days with quick dry, RUCO bac Med antiperspirant UVP 50+ protection, breathable, moisture wicking. The simple design with round neck and small reflected print at side seam, makes it easy to combine and is ideal for teams and crews or",
      "url": "https://waypointuae.com/products/ACTIVE-2-LONG-SLEEVE-p524632004",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691044113.jpg",
      "width": 555,
      "height": 564,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "ACTIVE 2 LONG SLEEVE",
        "url": "https://waypointuae.com/products/ACTIVE-2-LONG-SLEEVE-p524632004",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691044114.jpg",
        "width": 394,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691044114.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/ACTIVE-2-LONG-SLEEVE-p524632004",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "CAPTAIN NON-IRON SHIRT WOMEN",
    "brand": "Marinepool",
    "price": 320,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Crew Wear by Marinepool – the Captain Non-iron Shirt for women. Marinepool has a wide range of crew and work wear for yachts of all sizes. We also offer suitable workwear for women. Marinepool has developed the Captain blouse specifically for use on superyachts. In addition to the modern cut, the blouse has a front button placket, a Kent collar and two chest pockets and as well epaulettes. As a",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CAPTAIN NON-IRON SHIRT WOMEN",
      "name": "CAPTAIN NON-IRON SHIRT WOMEN",
      "description": "Crew Wear by Marinepool – the Captain Non-iron Shirt for women. Marinepool has a wide range of crew and work wear for yachts of all sizes. We also offer suitable workwear for women. Marinepool has developed the Captain blouse specifically for use on superyachts. In addition to the modern cut, the blouse has a front button placket, a Kent collar and two chest pockets and as well epaulettes. As a",
      "url": "https://waypointuae.com/products/CAPTAIN-NON-IRON-SHIRT-WOMEN-p524454797",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3424515001.jpg",
      "width": 541,
      "height": 690,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CAPTAIN NON-IRON SHIRT WOMEN",
        "url": "https://waypointuae.com/products/CAPTAIN-NON-IRON-SHIRT-WOMEN-p524454797",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3424515002.jpg",
        "width": 314,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3424515002.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CAPTAIN-NON-IRON-SHIRT-WOMEN-p524454797",
    "active": "true"
  },
  {
    "category": "chef-wear",
    "name": "CHEF JACKET LONG SLEEVE",
    "brand": "Just Adore UAE",
    "price": 250,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Chef Coat \n \n \n \nMade from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n DESCRIPTION: \n \n Content : 60% Cotton 40% Polyester \n Unisex - Men & Women \n GSM : 220 \n Fabric : Plain weave \n Fit : Regular Fit",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "chef-jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CHEF JACKET LONG SLEEVE",
      "name": "CHEF JACKET LONG SLEEVE",
      "description": "Chef Coat \n \n \n \nMade from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n DESCRIPTION: \n \n Content : 60% Cotton 40% Polyester \n Unisex - Men & Women \n GSM : 220 \n Fabric : Plain weave \n Fit : Regular Fit",
      "url": "https://waypointuae.com/products/CHEF-JACKET-LONG-SLEEVE-p526997738",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3437493345.jpg",
      "width": 1000,
      "height": 1000,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CHEF JACKET LONG SLEEVE",
        "url": "https://waypointuae.com/products/CHEF-JACKET-LONG-SLEEVE-p526997738",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3437493346.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3437493346.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CHEF-JACKET-LONG-SLEEVE-p526997738",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "BURT NON-IRON SHIRT MEN",
    "brand": "Marinepool",
    "price": 322,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "SKU: 1004149 FABRIC: 100% cotton (Oxford) FEATURES: Burt – the short-sleeved non-iron men's shirt from Marinepool. The classic shirt for hot summer days! The Burt Shirt comes in 100% cotton Oxford quality with innovative non-iron technology. A special feature of this technology is that even a 100% cotton shirt does not have to be ironed after washing and is still smooth. The premium shirt has a",
    "fit": "woman|man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "BURT NON-IRON SHIRT MEN",
      "name": "BURT NON-IRON SHIRT MEN",
      "description": "SKU: 1004149 FABRIC: 100% cotton (Oxford) FEATURES: Burt – the short-sleeved non-iron men's shirt from Marinepool. The classic shirt for hot summer days! The Burt Shirt comes in 100% cotton Oxford quality with innovative non-iron technology. A special feature of this technology is that even a 100% cotton shirt does not have to be ironed after washing and is still smooth. The premium shirt has a",
      "url": "https://waypointuae.com/products/BURT-NON-IRON-SHIRT-MEN-p521715525",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406585302.jpg",
      "width": 460,
      "height": 690,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "BURT NON-IRON SHIRT MEN",
        "url": "https://waypointuae.com/products/BURT-NON-IRON-SHIRT-MEN-p521715525",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406585303.jpg",
        "width": 267,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3406585303.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/BURT-NON-IRON-SHIRT-MEN-p521715525",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "CAPTAIN SHIRT SS NON-IRON",
    "brand": "Marinepool",
    "price": 320,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "The Marinepool Captain Non-iron Shirt – the perfect shirt for captains and crew wear! The Captain Shirt is the ideal choice for all captains and officers. It is characterized not only by the special design with the epaulettes and the breast pockets, but also by the functionality. Thanks to the innovative non-iron technology, this shirt is perfect for crews. Simply shake it up after washing, let it",
    "fit": "woman|man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CAPTAIN SHIRT SS NON-IRON",
      "name": "CAPTAIN SHIRT SS NON-IRON",
      "description": "The Marinepool Captain Non-iron Shirt – the perfect shirt for captains and crew wear! The Captain Shirt is the ideal choice for all captains and officers. It is characterized not only by the special design with the epaulettes and the breast pockets, but also by the functionality. Thanks to the innovative non-iron technology, this shirt is perfect for crews. Simply shake it up after washing, let it",
      "url": "https://waypointuae.com/products/CAPTAIN-SHIRT-SS-NON-IRON-p529453342",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3647376021.jpg",
      "width": 1038,
      "height": 1172,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CAPTAIN SHIRT SS NON-IRON",
        "url": "https://waypointuae.com/products/CAPTAIN-SHIRT-SS-NON-IRON-p529453342",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3647376022.jpg",
        "width": 354,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3647376022.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CAPTAIN-SHIRT-SS-NON-IRON-p529453342",
    "active": "true"
  },
  {
    "category": "accessories",
    "name": "CHEF CAP - SKULL",
    "brand": "Just Adore UAE",
    "price": 95,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "cap",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CHEF CAP - SKULL",
      "name": "CHEF CAP - SKULL",
      "description": "",
      "url": "https://waypointuae.com/products/CHEF-CAP-SKULL-p533571815",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3478997641.jpg",
      "width": 600,
      "height": 600,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CHEF CAP - SKULL",
        "url": "https://waypointuae.com/products/CHEF-CAP-SKULL-p533571815",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3478997642.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3478997642.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CHEF-CAP-SKULL-p533571815",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "DECKVEST LITE LIFE JKT",
    "brand": "Spinlock",
    "price": 997,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "About the item \n \n Deckvest LITE+ available in Black Graphite and New Sun Yellow \n Designed for the perfect fit - every time \n Lightweight low profile \n Durable honeycomb ripstop cover fabric \n Automatic inflating lifejacket \n 170N (38lbs) buoyancy \n Easy side donning \n One size \n Single crotch strap with recessed clip reduces risk of snagging \n Deckvest LITE+ has an integrated deck safety harness",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "DECKVEST LITE LIFE JKT",
      "name": "DECKVEST LITE LIFE JKT",
      "description": "About the item \n \n Deckvest LITE+ available in Black Graphite and New Sun Yellow \n Designed for the perfect fit - every time \n Lightweight low profile \n Durable honeycomb ripstop cover fabric \n Automatic inflating lifejacket \n 170N (38lbs) buoyancy \n Easy side donning \n One size \n Single crotch strap with recessed clip reduces risk of snagging \n Deckvest LITE+ has an integrated deck safety harness",
      "url": "https://waypointuae.com/products/DECKVEST-LITE-LIFE-JKT-p560129336",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3642904031.jpg",
      "width": 203,
      "height": 203,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "DECKVEST LITE LIFE JKT",
        "url": "https://waypointuae.com/products/DECKVEST-LITE-LIFE-JKT-p560129336",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3642904032.jpg",
        "width": 203,
        "height": 203
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3642904032.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/DECKVEST-LITE-LIFE-JKT-p560129336",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "CAPTAIN JACKET KNIT SWEATER MEN",
    "brand": "Marinepool",
    "price": 600,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Cardigan with a zip The Captain jacket knit sweater for men by Marinepool is a unique feature in your new Marinepool collection. It has an inner lining that is windproof so you are optimally protected even on stormy days. The collar supports the wearing comfort of the cardigan. The zip allows you to put the cardigan on and take it off easily. There are elasticated cuffs on the sleeves and the",
    "fit": "woman|man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CAPTAIN JACKET KNIT SWEATER MEN",
      "name": "CAPTAIN JACKET KNIT SWEATER MEN",
      "description": "Cardigan with a zip The Captain jacket knit sweater for men by Marinepool is a unique feature in your new Marinepool collection. It has an inner lining that is windproof so you are optimally protected even on stormy days. The collar supports the wearing comfort of the cardigan. The zip allows you to put the cardigan on and take it off easily. There are elasticated cuffs on the sleeves and the",
      "url": "https://waypointuae.com/products/CAPTAIN-JACKET-KNIT-SWEATER-MEN-p541101671",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3521767445.jpg",
      "width": 1200,
      "height": 1388,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CAPTAIN JACKET KNIT SWEATER MEN",
        "url": "https://waypointuae.com/products/CAPTAIN-JACKET-KNIT-SWEATER-MEN-p541101671",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3521767446.jpg",
        "width": 346,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3521767446.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CAPTAIN-JACKET-KNIT-SWEATER-MEN-p541101671",
    "active": "true"
  },
  {
    "category": "chef-wear",
    "name": "CHEF JACKET SHORT SLEEVE",
    "brand": "Just Adore UAE",
    "price": 135,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Made from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n \n \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n DESCRIPTION: \n \n Content : 60% Cotton 40% Polyester \n Unisex - Men & Women \n GSM : 220 \n Fabric : Plain weave \n Fit : Regular Fit",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "chef-jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CHEF JACKET SHORT SLEEVE",
      "name": "CHEF JACKET SHORT SLEEVE",
      "description": "Made from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n \n \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n DESCRIPTION: \n \n Content : 60% Cotton 40% Polyester \n Unisex - Men & Women \n GSM : 220 \n Fabric : Plain weave \n Fit : Regular Fit",
      "url": "https://waypointuae.com/products/CHEF-JACKET-SHORT-SLEEVE-p581825862",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234443021.jpg",
      "width": 381,
      "height": 515,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CHEF JACKET SHORT SLEEVE",
        "url": "https://waypointuae.com/products/CHEF-JACKET-SHORT-SLEEVE-p581825862",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234443022.jpg",
        "width": 296,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234443022.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CHEF-JACKET-SHORT-SLEEVE-p581825862",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "CARLOS BLAZER MEN",
    "brand": "Marinepool",
    "price": 765,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "SKU: 1003820 FABRIC: 100% polyester FEATURES: Winner in elegance and function - the innovative Carlos Blazer by Marinepool. Especially for summer events such as award ceremonies or prize giving a sportive-elegant blazer is indispensable. But in all known blazers such an event becomes a torment. Sweating and the ensuing discomfort kills the mood on a beautiful summery day. But this is exactly where",
    "fit": "woman|man",
    "roleTags": [
      "captain",
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CARLOS BLAZER MEN",
      "name": "CARLOS BLAZER MEN",
      "description": "SKU: 1003820 FABRIC: 100% polyester FEATURES: Winner in elegance and function - the innovative Carlos Blazer by Marinepool. Especially for summer events such as award ceremonies or prize giving a sportive-elegant blazer is indispensable. But in all known blazers such an event becomes a torment. Sweating and the ensuing discomfort kills the mood on a beautiful summery day. But this is exactly where",
      "url": "https://waypointuae.com/products/CARLOS-BLAZER-MEN-p584622045",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888837261.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CARLOS BLAZER MEN",
        "url": "https://waypointuae.com/products/CARLOS-BLAZER-MEN-p584622045",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888837262.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3888837262.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CARLOS-BLAZER-MEN-p584622045",
    "active": "true"
  },
  {
    "category": "bottoms",
    "name": "CHEF TROUSERS",
    "brand": "Just Adore UAE",
    "price": 200,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Chef Trouser. \n Shop Chef Trousers. Shop Restaurant Uniforms U.A.E online. Find Best Sellers Men's Chef Trousers. Browse Chef Coats, Aprons, Chef Hats collections. \n \n \nMade from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n",
    "fit": "woman|man",
    "roleTags": [
      "chef"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shorts",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CHEF TROUSERS",
      "name": "CHEF TROUSERS",
      "description": "Chef Trouser. \n Shop Chef Trousers. Shop Restaurant Uniforms U.A.E online. Find Best Sellers Men's Chef Trousers. Browse Chef Coats, Aprons, Chef Hats collections. \n \n \nMade from 60% Cotton, 40% Polyester, Twill weave. Everyday use. \n FEATURES: \n \n \n \n Light weight Fabric, Breathable, Soft Feel. \n Fits True to size - Regular Fit \n Machine Wash in Cold water, Wash Like colors Separate. \n \n",
      "url": "https://waypointuae.com/products/CHEF-TROUSERS-p532444279",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3472017611.jpg",
      "width": 1000,
      "height": 1000,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CHEF TROUSERS",
        "url": "https://waypointuae.com/products/CHEF-TROUSERS-p532444279",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3472017612.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3472017612.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CHEF-TROUSERS-p532444279",
    "active": "true"
  },
  {
    "category": "outerwear",
    "name": "AMICA FLEECE JACKET W",
    "brand": "Marinepool",
    "price": 545,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "Amica is a sporty fleecejacket in the new colorways of the winter saison. This maritime-inspired women’s fleece jacket is made from cozy polyester fabric with anti pilling effect. With contrast colour zip and marinepool badge on the left sleeve. Amica is the perfect winter fleece for a maritime look! • high quality fleece fabric • contrast colour zip • maritime details",
    "fit": "woman|man",
    "roleTags": [
      "interior",
      "chief-stew"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "jacket",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "AMICA FLEECE JACKET W",
      "name": "AMICA FLEECE JACKET W",
      "description": "Amica is a sporty fleecejacket in the new colorways of the winter saison. This maritime-inspired women’s fleece jacket is made from cozy polyester fabric with anti pilling effect. With contrast colour zip and marinepool badge on the left sleeve. Amica is the perfect winter fleece for a maritime look! • high quality fleece fabric • contrast colour zip • maritime details",
      "url": "https://waypointuae.com/products/AMICA-FLEECE-JACKET-W-p533567464",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691105627.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "AMICA FLEECE JACKET W",
        "url": "https://waypointuae.com/products/AMICA-FLEECE-JACKET-W-p533567464",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691105628.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3691105628.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/AMICA-FLEECE-JACKET-W-p533567464",
    "active": "true"
  },
  {
    "category": "shirts",
    "name": "CAPTAIN NONIRON SHIRT LONG MEN",
    "brand": "Marinepool",
    "price": 370,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "SKU: 1004216 FABRIC: 100% cotton FEATURES: The Marinepool Captain Non-iron Shirt – the perfect shirt for captains and crew wear! The Captain Shirt is the perfect choice for all captains and officers. It is characterized not only by the special design with the epaulettes and the breast pockets, but also by the functionality. Thanks to the innovative non-iron technology, this shirt is perfect for",
    "fit": "woman|man",
    "roleTags": [
      "captain"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "shirt",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CAPTAIN NONIRON SHIRT LONG MEN",
      "name": "CAPTAIN NONIRON SHIRT LONG MEN",
      "description": "SKU: 1004216 FABRIC: 100% cotton FEATURES: The Marinepool Captain Non-iron Shirt – the perfect shirt for captains and crew wear! The Captain Shirt is the perfect choice for all captains and officers. It is characterized not only by the special design with the epaulettes and the breast pockets, but also by the functionality. Thanks to the innovative non-iron technology, this shirt is perfect for",
      "url": "https://waypointuae.com/products/CAPTAIN-NONIRON-SHIRT-LONG-MEN-p584415507",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3850480761.jpg",
      "width": 540,
      "height": 540,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CAPTAIN NONIRON SHIRT LONG MEN",
        "url": "https://waypointuae.com/products/CAPTAIN-NONIRON-SHIRT-LONG-MEN-p584415507",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3850480762.jpg",
        "width": 400,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/3850480762.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CAPTAIN-NONIRON-SHIRT-LONG-MEN-p584415507",
    "active": "true"
  },
  {
    "category": "tops",
    "name": "CHAMP SMOCK 2.0",
    "brand": "Musto",
    "price": 1050,
    "currency": "AED",
    "vatRate": 0,
    "colours": "",
    "swatch": "#ffffff",
    "accent": "#0b1f3a",
    "fabric": "",
    "details": "A stretchy and protective smock built for fast-paced inshore sailing. Superior freedom of movement and 5k/5k waterproof protection. \n \n \n \n COMPOSITION \n \n Shell: 89% Polyester, 11% Elastane - Shell 2: 100% Polyurethane - Shell 3: 100% Neoprene \n \n \n \n EXPLORE ALL FEATURES \n \n \n \n Bi-stretch 3-layer 5k/5k fabric \n Asymmetric YKK® AquaGuard® 1/2 zip opening with self-fabric zip gusset to prevent",
    "fit": "woman|man",
    "roleTags": [
      "deck"
    ],
    "leadTime": "",
    "minOrder": 1,
    "sizeRange": "",
    "imageHint": "polo",
    "imageUrl": {
      "@type": "ImageObject",
      "caption": "CHAMP SMOCK 2.0",
      "name": "CHAMP SMOCK 2.0",
      "description": "A stretchy and protective smock built for fast-paced inshore sailing. Superior freedom of movement and 5k/5k waterproof protection. \n \n \n \n COMPOSITION \n \n Shell: 89% Polyester, 11% Elastane - Shell 2: 100% Polyurethane - Shell 3: 100% Neoprene \n \n \n \n EXPLORE ALL FEATURES \n \n \n \n Bi-stretch 3-layer 5k/5k fabric \n Asymmetric YKK® AquaGuard® 1/2 zip opening with self-fabric zip gusset to prevent",
      "url": "https://waypointuae.com/products/CHAMP-SMOCK-2-0-p586370001",
      "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234447521.jpg",
      "width": 342,
      "height": 433,
      "thumbnail": {
        "@type": "ImageObject",
        "caption": "CHAMP SMOCK 2.0",
        "url": "https://waypointuae.com/products/CHAMP-SMOCK-2-0-p586370001",
        "contentUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234447522.jpg",
        "width": 316,
        "height": 400
      },
      "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/82807564/4234447522.jpg"
    },
    "colourImages": "",
    "supplierName": "Waypoint UAE",
    "productUrl": "https://waypointuae.com/products/CHAMP-SMOCK-2-0-p586370001",
    "active": "true"
  }
];
